/*
* generated by github.com/calgagi/cp_gen
* author: weiyutang
* file: A.cpp
* time: Fri Feb 19 14:35:42 2021
*/

#include <bits/stdc++.h>
using namespace std;


#define ll long long
#define ld long double
#define ii pair<int, int>
#define f first
#define s second
#define endl "\n"

void solve() {
    int r, c;
    cin >> r >> c;
    vector<string> v(r);
    for(int i = 0; i < r; i++) cin >> v[i];

    unordered_set<int> row, col;
    for (int i = 0; i < r; i++) {
        for (int j = 0; j < c; j++) {
            if (v[i][j] == 'S') {
                row.insert(i);
                col.insert(j);
            }
        }
    }

    cout << (r * c) - (int)(row.size() * col.size()) << endl;
}

int main() {
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    srand(chrono::steady_clock::now().time_since_epoch().count());

    int t = 1;
    // cin >> t;
    
    while (t--) {
        solve();
    }

    cerr << "time taken : " << (float)clock() / CLOCKS_PER_SEC << " secs" << endl; 
    return 0;
}
