/*
 * generated by github.com/calgagi/cp_gen
 * author: weiyutang
 * file: A.cpp
 * time: Fri Mar 12 21:58:43 2021
 */

#include <bits/stdc++.h>
using namespace std;
const string CP_GEN_FILE = "A";

namespace cp {

}

/* ===== BEGIN USER CODE ===== */

#define ll long long
#define ld long double
#define ii pair<int, int>
#define f first
#define s second
#define endl "\n"

void solve() {
    int n;
    cin >> n;
    map<int, int> mp;
    for (int i = 0; i < n; i++) {
        int x; cin >> x;
        mp[x]++;
    }

    vector<int> v(n);
    int i = 0;
    for (auto& x: mp) {
        v[i] = x.f;
        i++;
    }

    for (auto& x: mp) {
        for (int j = 0; j < max(0, x.s - 1); j++) {
            v[i] = x.f;
            i++;
        }
    }

    for (int& x: v) cout << x << " ";
    cout << endl;
}

int main() {
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    srand(chrono::steady_clock::now().time_since_epoch().count());

    int t = 1;
    cin >> t;
    
    while (t--) {
        solve();
    }

    cerr << "time taken : " << (float)clock() / CLOCKS_PER_SEC << " secs" << endl; 
    return 0;
}
