/*
 * generated by github.com/calgagi/cp_gen
 * author: weiyutang
 * file: C.cpp
 * time: Fri Feb 19 14:35:40 2021
 */

#include <bits/stdc++.h>
using namespace std;
const string CP_GEN_FILE = "C";

namespace cp {

}

/* ===== BEGIN USER CODE ===== */

#define ll long long
#define ld long double
#define ii pair<int, int>
#define f first
#define s second
#define endl "\n"

void solve() {
    int n, k;
    cin >> n >> k;

    for (int i = 0; i < k - 3; i++) {
        cout << 1 << " ";
    }

    n -= k - 3;
    if (n & 1) {
        int a = n / 2;
        int b = 1;
        cout << a << " " << a << " " << b << endl;
    } else {
        if ((n / 2) & 1) {
            int a = 2;
            int b = (n - a) / 2;
            cout << a << " " << b << " " << b << endl;
        } else {
            int a = n / 2;
            int b = n / 4;
            cout << a << " " << b << " " << b << endl;
        }
    } 
}

int main() {
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    srand(chrono::steady_clock::now().time_since_epoch().count());

    int t = 1;
    cin >> t;
    
    while (t--) {
        solve();
    }

    cerr << "time taken : " << (float)clock() / CLOCKS_PER_SEC << " secs" << endl; 
    return 0;
}
