/*
 * generated by github.com/calgagi/cp_gen
 * author: weiyutang
 * file: A.cpp
 * time: Thu Feb 18 01:22:27 2021
 */

#include <bits/stdc++.h>
using namespace std;
const string CP_GEN_FILE = "A";

namespace cp {

}

/* ===== BEGIN USER CODE ===== */

#define ll long long
#define ld long double
#define ii pair<int, int>
#define f first
#define s second
#define endl "\n"

void solve() {
    int n;
    cin >> n;
    vector<int> v(n);
    for (int& x: v) cin >> x;

    int64_t curr = 0;
    for (int i = 0; i < n; i++) {
        curr += v[i];
        if (curr < i) {
            cout << "NO" << endl;
            return;
        }
        curr -= i;
    }

    cout << "YES" << endl;
    return;
}

int main() {
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    srand(chrono::steady_clock::now().time_since_epoch().count());

    int t = 1;
    cin >> t;
    
    while (t--) {
        solve();
    }

    return 0;
}
