/*
 * generated by github.com/calgagi/cp_gen
 * author: weiyutang
 * file: D.cpp
 * time: Fri Feb 19 14:35:42 2021
 */

#include <bits/stdc++.h>
using namespace std;
const string CP_GEN_FILE = "D";

namespace cp {

}

/* ===== BEGIN USER CODE ===== */

#define ll long long
#define ld long double
#define ii pair<int, int>
#define f first
#define s second
#define endl "\n"

void solve() {
    int64_t n;
    cin >> n;
    vector<int> v(n);
    for (int& x: v) cin >> x;

    map<int, int> mp;
    for (int i = 0; i < n; i++) {
        mp[v[i]]++;
    }

    auto x = max_element(mp.begin(), mp.end(), [] (const pair<int, int>& p1, const pair<int, int>& p2) {
                return p1.second < p2.second;
            });

    cout << n - 2 * min(n / 2, n - x->s) << endl;
}

int main() {
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    srand(chrono::steady_clock::now().time_since_epoch().count());

    int t = 1;
    cin >> t;
    
    while (t--) {
        solve();
    }

    cerr << "time taken : " << (float)clock() / CLOCKS_PER_SEC << " secs" << endl; 
    return 0;
}
