/*
 * generated by github.com/calgagi/cp_gen
 * author: weiyutang
 * file: B.cpp
 * time: Fri Feb 19 14:35:38 2021
 */

#include <bits/stdc++.h>
using namespace std;
const string CP_GEN_FILE = "B";

namespace cp {

}

/* ===== BEGIN USER CODE ===== */

#define ll long long
#define ld long double
#define ii pair<int, int>
#define f first
#define s second
#define endl "\n"

void solve() {
    int n, k;
    string st;
    cin >> n >> k >> st;

    int idx;
    for (idx = 0; idx < n; idx++) {
        if (st[idx] == '*') {
            st[idx] = 'x';
            break;
        }
    }

    int ans = 1;

    for (int i = idx; i < n; i++) {
        for (int j = i + k; j > i; j--) {
            if (j < n && st[j] == '*') {
                ans++;
                st[j] = 'x';
                i = j - 1;
                break;
            }
        }
    }

    cout << ans << endl;
    return;
}

int main() {
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    srand(chrono::steady_clock::now().time_since_epoch().count());

    int t = 1;
    cin >> t;
    
    while (t--) {
        solve();
    }

    cerr << "time taken : " << (float)clock() / CLOCKS_PER_SEC << " secs" << endl; 
    return 0;
}
