/*
 * generated by github.com/calgagi/cp_gen
 * author: weiyutang
 * file: A.cpp
 * time: Fri Feb 19 14:35:40 2021
 */

#include <bits/stdc++.h>
using namespace std;

/* ===== BEGIN USER CODE ===== */

#define ll long long
#define ld long double
#define ii pair<int, int>
#define f first
#define s second
#define endl "\n"

const int MOD = 1e9 + 7;
const vector<ii> dir {{0, 1}, {1, 0}, {-1, 0}, {0, -1}};

void part2() {
    cout << "Part 2: " << endl;

    string st;
    int64_t hor = 0, aim = 0, depth = 0;
    while (getline(cin, st)) {
        int n = st.size();
        int num = st[n-1] - '0';

        if (st[0] == 'f') {
            hor += num;
            depth += (aim * num);
        } else if (st[0] == 'u') {
            aim -= num;
        } else {
            aim += num;
        }
    }
    cout << hor << " " << depth << " " << hor * depth << endl;
}

void part1() {
    cout << "Part 1: " << endl;

    string st;
    int64_t hor = 0, depth =  0;
    while (getline(cin, st)) {
        int n = st.size();
        int num = st[n - 1] - '0';

        if (st[0] == 'f') {
            hor += num;
        } else if (st[0] == 'u') {
            depth -= num;
        } else {
            depth += num;
        }
    }
    cout << hor << " " << depth << " " << hor * depth << endl;
}


int main() {
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    srand(chrono::steady_clock::now().time_since_epoch().count());

    int t = 1;
    //cin >> t;
    
    while (t--) {
        //part1();
        cout << endl;
        part2();
    }

    cerr << "time taken : " << (float)clock() / CLOCKS_PER_SEC << " secs" << endl; 
    return 0;
}
