/*
* generated by github.com/calgagi/cp_gen
* author: weiyutang
* file: A.cpp
* time: Fri Feb 19 14:35:42 2021
*/

#include <bits/stdc++.h>
using namespace std;


#define ll long long
#define ld long double
#define ii pair<int, int>
#define f first
#define s second
#define endl "\n"

bool valid(string br) {
    int n = br.size();
    stack<int> st;
    for (int i = 0; i < n; i++) {
        if (br[i] == '(') {
            st.push(1);
        } else {
            if (st.empty()) return false;
            st.pop();
        }
    }
    return st.size() == 0;
}

bool convert(string st, vector<int>& c) {
    string br = "";
    int n = st.size();
    for (int i = 0; i < n; i++) {
        if ((st[i] == 'A' && c[0] == 1) || 
            (st[i] == 'B' && c[1] == 1) ||
            (st[i] == 'C' && c[2] == 1))
            br += '(';
        else
            br += ')';
    }

    return valid(br);
}

void solve() {
    string st;
    cin >> st;

    vector<vector<int>> combinations {{1,0,1},{1,1,0},{0,1,1},{0,1,0},{1,0,0},{0,0,1}};
    bool found = false;
    for (int i = 0; i < 6; i++) {
        if (convert(st, combinations[i])) {
            found = true;
            break;
        } 
    }

    if (found) cout << "YES" << endl;
    else cout << "NO" << endl;

}

int main() {
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    srand(chrono::steady_clock::now().time_since_epoch().count());

    int t = 1;
    cin >> t;
    
    while (t--) {
        solve();
    }

    cerr << "time taken : " << (float)clock() / CLOCKS_PER_SEC << " secs" << endl; 
    return 0;
}
