/*
 * generated by github.com/calgagi/cp_gen
 * author: weiyutang
 * file: B.cpp
 * time: Fri Feb 19 14:35:38 2021
 */

#include <bits/stdc++.h>
using namespace std;
const string CP_GEN_FILE = "B";

namespace cp {

}

/* ===== BEGIN USER CODE ===== */

#define ll long long
#define ld long double
#define ii pair<int, int>
#define f first
#define s second
#define endl "\n"

void solve() {
    int n;
    cin >> n;
    vector<int> dir(4); // U R D L
    for (int& x: dir) cin >> x;

    for (int i = 0; i < 16; i++) {
        vector<int> temp(dir); // U R D L
        if (i & 1) { // Top left corner
            temp[0]--, temp[3]--;
        }
        if (i & 2) { // Bottom left corner
            temp[2]--, temp[3]--;
        }
        if (i & 4) { // Top right corner
            temp[0]--, temp[1]--;
        }
        if (i & 8) { // Bottom right corner
            temp[2]--, temp[1]--;
        }

        int max_n = 0, min_n = INT_MAX;
        for (int i = 0; i < 4; i++) {
            max_n = max(max_n, temp[i]);
            min_n = min(min_n, temp[i]);
        }
        if (max_n <= n - 2 && min_n >= 0) {
            cout << "YES" << endl;
            return;
        }
    }

    cout << "NO" << endl;
    return;
    
}

int main() {
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    srand(chrono::steady_clock::now().time_since_epoch().count());

    int t = 1;
    cin >> t;
    
    while (t--) {
        solve();
    }

    cerr << "time taken : " << (float)clock() / CLOCKS_PER_SEC << " secs" << endl; 
    return 0;
}
