/*
 * generated by github.com/calgagi/cp_gen
 * author: weiyutang
 * file: B.cpp
 * time: Fri Feb 19 14:35:38 2021
 */

#include <bits/stdc++.h>
using namespace std;
const string CP_GEN_FILE = "B";

namespace cp {

}

/* ===== BEGIN USER CODE ===== */

#define ll long long
#define ld long double
#define ii pair<int, int>
#define f first
#define s second
#define endl "\n"

int MOD = 1e9 + 7;

void solve() {
    int a, b, c, m;
    cin >> a >> b >> c >> m;

    int t = m - (a-1) - (b-1) - (c-1);

    if (t > 0) {
        cout << "NO" << endl;
        return;
    }

    int max_n = max(a, max(b, c));
    if (a == max_n && b + c >= (a - 1) - m) {
        cout << "YES" << endl;
        return;
    }
    if (b == max_n && a + c >= (b - 1) - m) {
        cout << "YES" << endl;
        return;
    }
    if (c == max_n && a + b >= (c - 1) - m) {
        cout << "YES" << endl;
        return;
    }

    cout << "NO" << endl;

}

int main() {
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    srand(chrono::steady_clock::now().time_since_epoch().count());

    int t = 1;
    cin >> t;

    while (t--) {
        solve();
    }

    cerr << "time taken : " << (float)clock() / CLOCKS_PER_SEC << " secs" << endl; 
    return 0;
}

